#Purpose: code for the UI for the Interactive Map, a shiny app

# Define UI for application
dashboardPage(
  dashboardHeader(disable = TRUE),
  dashboardSidebar(disable = TRUE),
  dashboardBody(
    tags$head(
      tags$script(HTML("
          $(document).keyup(function(event) {
            if (event.keyCode == 13) { // 13 is the Enter key code
              $('#password_submit').click(); // Replace 'myActionButton' with your button's inputId
            }
          });
        "))
    ),
    tabsetPanel(
      id = "mainPanel",

      #First tab - Purpose and Disclaimer----
      tabPanel(
        title = "Purpose and Disclaimer",
        fluidRow(
          box(width = 8, h2("Purpose"), 
          p("The", tags$b("Central Sands Groundwater Tracker")," is a web application (app) designed by the Wisconsin Geologic 
            and Natural History Survey (WGNHS) to visualize the flow direction, contributing zones, and transit times of 
            groundwater in Wisconsin’s Central Sands."),
          p("The app was created as an educational tool and can be used to: (1) identify contributing areas for groundwater in a 
            given area, (2) understand how long groundwater may take to travel to a given area, (3) identify the land cover at the 
            start of an identified groundwater flow path, and (4) inform how long it may take for changes in land use or management
            to impact groundwater in a given area."),
          p("The app does not identify which groundwater flow paths are accessed by any specific well. The app also does not 
            inform users of how land use along a groundwater flow path may affect the water quality."),
          p("The app is only a representation of groundwater flow in the Central Sands generated by a computer model of groundwater 
            flow for the region (see the ", tags$b("Model Assumptions")," tab for more information). It is not applicable outside of the model 
            area (gray outline on the ", tags$b("Interactive Map")," tab) or for overland flow characteristics. The WGNHS is not responsible for 
            misuse or misrepresentation of the data."),
          p("The app was created using R statistical programming and Shiny programming that visualize MODPATH output and Wiscland data. 
          It was created by the WGNHS with input and review by staff at UW–Madison Division of Extension and Portage County.")
          )
        ),
        fluidRow(
          box(width = 8, h2("Questions"), "For questions about the app, contact ", tags$b("Dave Hart")," (djhart@wisc.edu) at WGNHS or" , 
          tags$b("Jennifer McNelly")," (jennifer.mcnelly@wisc.edu) at Wood County Extension.")
        ),
        fluidRow(
          box(width = 8, h2("How to Use"), "Select the ", tags$b("Interactive Map")," tab above to bring up a map of the Central Sands. 
              Then select a point within the gray outline of the Central Sands to see predicted flow paths, land cover, and transit times.")
        ),
        fluidRow(
          box(width = 8, h2("Disclaimer"), "This representation of flow paths, land use, and transit times in the Central Sands of Wisconsin is provided by the WGNHS on an as is basis. 
              WGNHS will not be liable for any damages of any kind arising from the use of these data, including, but not limited to direct, indirect, punitive, and consequential.
              WGNHS makes no warranties on these data, express, implied, statutory, or in any other provision of any agreement or communication,
              and specifically disclaims any implied warranties of merchantability or fitness for a particular purpose.")
        ),
        fluidRow(
          column(width = 4, img(src = "CentralSandsFlowPaths_72ppi.png")),
          column(width = 4, img(src = "WGNHS_color-flush-150ppi_2inch.png")),
        )
        
      ),
      
      
      #Second tab - Interactive Display----
      tabPanel(
        title = "Interactive Map",
        fluidRow(
          box(width = 4, withSpinner(leafletOutput(outputId = "map", height = "500px"), caption = "Rendering Map..."), htmlOutput("mapExplainer")),
          box(width = 4, withSpinner(plotOutput(outputId = "landCoverBarPlot", height = "500px"), caption = "Determining Land Cover..."), htmlOutput("landCoverExplainer")),
          box(width = 4, withSpinner(plotOutput(outputId = "flowTimeHistogram", height = "500px"), caption ="Processing Transit Times..."), htmlOutput("transitTimeExplainer"))
          ),
        fluidRow(
          box(width = 10, h2("Data Sources and Limitations"),
          p("This app uses flow path and land cover data from peer reviewed sources. The flow paths are from Baker and others (2025) that 
            in turn were based on the groundwater model by Fienen and others (2022). The land cover data are from Wiscland 2.0, levels 1 
            and 3. See the", tags$b("Additional Resources")," tab for these references and more background information."), 
          p("The flow paths are model representations of the groundwater flows and as such cannot be expected to provide a perfect match 
          to actual groundwater movement. There can be error associated with the flow paths, including the timing and the start and end locations.
          "))
          )
        ),
      
      #Third tab - Model Assumptions----
      tabPanel(
        title = "Model Assumptions",
        fluidRow(
          box(width = 6, htmlOutput("modelAssumptions"))
          ),
        fluidRow(
          box(width = 6, h2("2D Versus 3D Flow Paths"), "The interactive map only shows horizontal groundwater flow paths. 
              In the real world, groundwater flow paths also move vertically. The figure below illustrates both horizontal 
              and vertical groundwater flow. Flow paths that start farther away from the discharge point move deeper while 
              those starting nearer the discharge point are shallower. The longer and deeper flow paths take more time to 
              reach their discharge points and so that groundwater is generally older. The shorter and shallower flow paths 
              take less time to reach their discharge points and so that groundwater is generally younger."),
          ),
        fluidRow(
          column(width = 6, imageOutput("groundWaterImage"),"Figure courtesy of the U.S. Geologic Survey. 
                 Source: https://doi.org/10.3133/fs06301.")
        )
        ),
      
      #Fourth tab - Additional Info----
      tabPanel(
        title = "Additional Resources",
        fluidRow(
          box(htmlOutput("externalLinks"))
        ),
        fluidRow(
          box(width = 6, h2("General Questions"), "For questions and more information about groundwater in the Central Sands, 
          contact ", tags$b("Dave Hart")," (djhart@wisc.edu) at WGNHS or " , tags$b("Jennifer McNelly")," (jennifer.mcnelly@wisc.edu)
          at Wood County Extension"),
        )
      )     
      
    )
    ),
  title = "Interactive Groundwater Flow Map"
)
